- name: Install distribution-gpg-keys package
  dnf:
    name: distribution-gpg-keys
    state: present

- name: Import rpm-gpg key of rpmfusion free repo
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/rpmfusion//RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}-primary'

- name: Import rpm-gpg key of rpmfusion nonfree repo
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/rpmfusion//RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}-primary'
- name: Import rpm-gpg key of adobe linux repo
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/adobe/RPM-GPG-KEY-adobe-linux'
- name: Install rpmfusion free repo
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Install rpmfusion nonfree repo
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Install adobe linux repo
  dnf:
    name: http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ ansible_userspace_architecture }}-1.0-1.noarch.rpm
    state: present

- name: "[Fedora] Update System"
  become_user: root
  dnf:
    name: "*"
    state: latest
    update_cache: yes
- name: "[Fedora] Install System Packages"
  become_user: root
  dnf:
    name: {{ dnf_packages }}
    state: latest

- name: Add Visual Studio Code Repo
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode

- name: Import Google Chrome signing key
  become: yes
  rpm_key: key=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present

- name: Add Visual Studio Code Repo
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode