- name: Install distribution-gpg-keys package
  become: yes
  dnf:
    name: distribution-gpg-keys
    state: present
- name: Import rpm-gpg key of rpmfusion free repo
  become: yes
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/rpmfusion//RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}-primary'
- name: Import rpm-gpg key of rpmfusion nonfree repo
  become: yes
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/rpmfusion//RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}-primary'
- name: Import rpm-gpg key of adobe linux repo
  become: yes
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/adobe/RPM-GPG-KEY-adobe-linux'
- name: Install rpmfusion free repo
  become: yes
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
- name: Install rpmfusion nonfree repo
  become: yes
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
- name: Install adobe linux repo
  become: yes
  dnf:
    name: http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ ansible_userspace_architecture }}-1.0-1.noarch.rpm
    state: present
- name: Install Google Chrome repo
  become: yes
  copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/
- name: Import Google Chrome signing key
  become: yes
  rpm_key:
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
- name: Add Visual Studio Code Repo
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
- name: Import Visual Studio Code signing key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: "[Fedora] Update System"
  become: yes
  dnf:
    name: "*"
    state: latest
    update_cache: yes
- name: "[Fedora] Install System Packages"
  become: yes
  dnf:
    name: "{{ dnf_packages }}"
    state: latest
- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present
- name: Install Visual Studio Code
  become: yes
  dnf:
    name: code
    state: present
