- name: Install distribution-gpg-keys package
  become: yes
  dnf:
    name: distribution-gpg-keys
    state: present
- name: Import rpm-gpg key of adobe linux repo
  become: yes
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/adobe/RPM-GPG-KEY-adobe-linux'
- name: Install adobe linux repo
  become: yes
  dnf:
    name: http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ ansible_userspace_architecture }}-1.0-1.noarch.rpm
    state: present
- name: Install Google Chrome repo
  become: yes
  copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/
- name: Import Google Chrome signing key
  become: yes
  rpm_key:
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
- name: Add Sublime Text Code Repo
  become: yes
  yum_repository:
    name: sublime-text
    description: Sublime Text Repo
    baseurl: https://download.sublimetext.com/rpm/dev/x86_64/sublime-text.repo
- name: Import Sublime Text Code signing key
  become: yes
  rpm_key:
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg 
    state: present
- name: Add Visual Studio Code Repo
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
- name: Import Visual Studio Code signing key
  become: yes
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: "[Fedora] Update System"
  become: yes
  dnf:
    name: "*"
    state: latest
    update_cache: yes
- name: "[Fedora] Install System Packages"
  become: yes
  dnf:
    name: "{{ dnf_packages }}"
    state: latest
- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present
- name: Install Visual Studio Code
  become: yes
  dnf:
    name: code
    state: present
- name: Install Sublime Text
  become: yes
  dnf:
    name: sublime-text
    state: present
- name: Install Sublime Merge
  become: yes
  dnf:
    name: sublime-merge
    state: present
