---
- hosts: localhost
  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Sudo password"
      private: yes
  tasks:
    - name: Check that we run on Fedora
      assert:
        that:
          - '"{{ ansible_distribution }}" == "Fedora"'
    