apt_packages:
  - autoconf
  - automake
  - binutils
  - bison
  - flex
  - gcc
  - libtool
  - make
  - emacs
  - htop
  - tidy
  - gitk
  - cmake
  - ripgrep
  - meld
  - cppcheck
  - gdb
  - ruby
  - neovim
  - kdiff3
  - sqlite
  - sqlitebrowser
  - golang
  - vagrant
  - virt-manager
  - virt-viewer
  - nmap
  - tmux
  - xsel
  - irssi
  - weechat
  - mutt
  - git
  - aspell
  - aspell-en
  - jq
  - bpftrace
  - strace
  - bcc
  - libtool
  - powertop
  - iotop
  - procps
  - vinagre
  - htop
  - mosh
  - tig
  - ack
  - earlyoom
  - smartmontools
  - curl
  - gnupg
  - tcpdump
  - screen
  - dstat
  - speedtest-cli
  - kitty
  - kitty-doc
  - kitty-terminfo
  - bat
  - exa
  - silversearcher-ag
  - fzf
  - glances
  - hyperfine
  - tldr

