- name: Set hostname to the model name
  command: >-
      bash -c "
        MODELNAME=$(dmidecode -s system-version | sed 's/[[:space:]]//g')
        if test \"$(hostname)\" != \"$MODELNAME\"; then
          hostnamectl set-hostname --static --pretty $MODELNAME
          echo 'Set hostname'
        fi"
  register: set_hostname
  changed_when: "'Set hostname' in set_hostname.stdout"
