- name: "[Fedora] Install terminator"
  become_user: root
  dnf:
    name:
      - terminator
    state: latest
- name: Creates terminator config directory
  file:
    path: "{{ ansible_user_dir }}/.config/terminator"
    state: directory
- name: copy terminator config
  copy: 
    src: config
    dest: "{{ ansible_user_dir }}/.config/terminator/config"
    owner: "{{ ansible_user_id }}"
    mode: 0664
