- name: "[Fedora] Install Kitty"
  become: yes
  dnf:
    name:
      - kitty
      - kitty-doc
      - kitty-terminfo
    state: latest
- name: Creates kitty config directory
  file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory
- name: copy kitty config
  copy: 
    src: kitty.conf
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    owner: "{{ ansible_user_id }}"
    mode: 0664
