- name: "[Fedora] Install terminator and tilix"
  become: yes
  dnf:
    name:
      - terminator
      - tilix
    state: latest
- name: Creates terminator config directory
  file:
    path: "{{ ansible_user_dir }}/.config/terminator"
    state: directory
- name: copy terminator config
  copy: 
    src: terminator_config
    dest: "{{ ansible_user_dir }}/.config/terminator/config"
    owner: "{{ ansible_user_id }}"
    mode: 0664
